[workspace]
resolver = "2"
members = [
    "src/battery-pack",
    "src/battery-pack-build",
    "src/battery-pack-cli",
    "src/error-battery-pack",
    "src/logging-battery-pack",
    "src/cli-battery-pack",
]
