[package]
name = "battery-pack"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cargo-bp"
path = "src/main.rs"

[dependencies]
battery-pack-build = { path = "../battery-pack-build" }
battery-pack-cli = { path = "../battery-pack-cli" }
anyhow = "1"

[dev-dependencies]
expect-test = "1"
