[template]
cargo_generate_version = ">=0.22.0"
ignore = ["hooks"]

[hooks]
pre = ["hooks/pre-script.rhai"]

[placeholders.description]
type = "string"
prompt = "What does this battery pack provide?"
default = "A battery pack for ..."
